### ISSUE TITLE
这个是大一的培训？

### ISSUE THREAD

**Issue by DrakeLeung** [JoeBBChen/Library-management-system#2]
我建议去刷 freecodecamp 。里面的东西比之前的 codeacademy 还要多。并且里面也有很多小项目，我觉得挺不错的。

你们也可以去刷。

**Comment by JoeBBChen** [comment]
是我自己练基础的。等我做出来了，再考虑要不要暑假叫他们做。freecodecamp，我去刷刷。thanks！！！
